import React from "react";
import Text from "@/components/constructor/text/Text";
import {
    COMPANY_NAME,
    COMPANY_LEGAL_NAME,
    COMPANY_NUMBER,
    COMPANY_ADDRESS,
    COMPANY_EMAIL,
} from "@/resources/constants";
import PolicyWrapper from "@/components/layout/policy-wrapper/PolicyWrapper";

export default function TermsPage() {
    return (
        <>
            <PolicyWrapper>
                <Text
                    title="Terms & Conditions"
                    bullets={[
                        "Effective date: 10 September 2025",
                        `These Terms and Conditions govern the use of ${COMPANY_NAME} and services operated by ${COMPANY_LEGAL_NAME}.`,
                    ]}
                />

                <Text
                    title="1. General Provisions"
                    bullets={[
                        `1.1. These Terms govern the use of ${COMPANY_NAME} and services provided by ${COMPANY_LEGAL_NAME} (Company No. ${COMPANY_NUMBER}), registered at ${COMPANY_ADDRESS}.`,
                        "1.2. By accessing the website, creating a CV draft, or purchasing token packages, you agree to these Terms.",
                        "1.3. If you do not agree with these Terms, you must not use the Services.",
                    ]}
                />

                <Text
                    title="2. Definitions"
                    bullets={[
                        "2.1. Services – tools and features allowing creation, editing, improvement, and export of CVs/resumes in PDF or DOCX format, including AI-assisted or human-supported services.",
                        "2.2. Draft – a preliminary version of a CV or resume created by the user.",
                        "2.3. Final File – the completed CV or resume downloaded by the user.",
                        "2.4. Client / you – any individual or entity using the Services.",
                        "2.5. Tokens – internal digital credits used to pay for Services (1 GBP or 1 EUR = 100 Tokens).",
                    ]}
                />

                <Text
                    title="3. Right to Use and Account Registration"
                    bullets={[
                        "3.1. You must be at least 18 years old or act with proper legal authority.",
                        "3.2. You must provide accurate and up-to-date information during registration.",
                        "3.3. You are responsible for maintaining confidentiality of your account credentials.",
                        "3.4. All activities performed through your account are your responsibility.",
                    ]}
                />

                <Text
                    title="4. Ordering, Tokens and Payment"
                    bullets={[
                        "4.1. Payments must be completed using the methods listed on the website.",
                        "4.2. Services become available only after successful payment.",
                        "4.3. Prices are displayed in GBP or EUR and may include applicable taxes.",
                        "4.4. Tokens represent prepaid access to digital Services and have no cash value.",
                    ]}
                />

                <Text
                    title="5. Service Delivery"
                    bullets={[
                        "5.1. Drafts and Final Files are generated automatically after Tokens are deducted.",
                        "5.2. You are responsible for reviewing Final Files immediately after delivery.",
                        "5.3. Additional edits or regenerations may require additional Tokens.",
                        "5.4. The Service is not intended for permanent document storage.",
                    ]}
                />

                <Text
                    title="6. Delivery of Digital Content"
                    bullets={[
                        "6.1. All Services result in digital content only. No physical documents are shipped.",
                        "6.2. Delivery is complete when Drafts or Final Files become available in your account or via download.",
                        "6.3. Outputs may be generated by artificial intelligence, human managers, or a combination of both.",
                        "6.4. Re-downloading the same file does not consume additional Tokens.",
                        "6.5. If delivery fails due to a technical issue attributable to us, Tokens may be restored or content regenerated.",
                        `6.6. Support requests must be sent to ${COMPANY_EMAIL} with relevant order details.`,
                    ]}
                />

                <Text
                    title="7. Cancellation and Refunds"
                    bullets={[
                        "7.1. Token packages may be canceled before use, subject to payment provider fees.",
                        "7.2. Tokens already used for Services are non-refundable.",
                        "7.3. Refunds or compensation may be issued in case of verified technical errors.",
                    ]}
                />

                <Text
                    title="8. Intellectual Property"
                    bullets={[
                        "8.1. You retain all rights to content you upload or enter.",
                        "8.2. We do not claim ownership over your content.",
                        "8.3. Generated Final Files belong to you once created.",
                    ]}
                />

                <Text
                    title="9. Confidentiality and Data Processing"
                    bullets={[
                        "9.1. Personal data is processed in accordance with UK GDPR and the Data Protection Act 2018.",
                        "9.2. Uploaded data may be deleted after processing unless required for support or legal obligations.",
                    ]}
                />

                <Text
                    title="10. Warranties and Disclaimer"
                    bullets={[
                        "10.1. Services are provided with reasonable care.",
                        "10.2. Services are provided on an “as is” basis.",
                        "10.3. We do not guarantee employment, interviews, or career outcomes.",
                    ]}
                />

                <Text
                    title="11. Limitation of Liability"
                    bullets={[
                        "11.1. We are not liable for indirect or consequential damages.",
                        "11.2. Total liability is limited to the amount paid for the relevant Token package.",
                    ]}
                />

                <Text
                    title="12. Indemnity"
                    bullets={[
                        "12.1. You agree to indemnify the Company against claims arising from misuse of the Services or breach of these Terms.",
                    ]}
                />

                <Text
                    title="13. Third-Party Links"
                    bullets={[
                        "13.1. We are not responsible for content or availability of third-party websites.",
                    ]}
                />

                <Text
                    title="14. Suspension and Termination"
                    bullets={[
                        "14.1. We may suspend or terminate accounts for breach, fraud, or security risks.",
                        "14.2. Termination does not entitle you to refunds for unused Tokens.",
                    ]}
                />

                <Text
                    title="15. Changes to These Terms"
                    bullets={[
                        "15.1. These Terms may be updated from time to time.",
                        "15.2. Continued use of the Service constitutes acceptance of updated Terms.",
                    ]}
                />

                <Text
                    title="16. Notices"
                    bullets={[
                        `16.1. Email: ${COMPANY_EMAIL}`,
                        `16.2. Address: ${COMPANY_ADDRESS}`,
                    ]}
                />

                <Text
                    title="17. Governing Law and Jurisdiction"
                    bullets={[
                        "17.1. These Terms are governed by the laws of England and Wales.",
                        "17.2. Courts of England and Wales have exclusive jurisdiction, subject to consumer protection laws.",
                    ]}
                />

                <Text
                    title="18. Miscellaneous"
                    bullets={[
                        "18.1. Invalid provisions do not affect the remainder of these Terms.",
                        "18.2. Failure to enforce a right does not constitute a waiver.",
                        "18.3. These Terms constitute the entire agreement between you and the Company.",
                    ]}
                />

                <Text
                    title="Company Details"
                    bullets={[
                        `Company: ${COMPANY_LEGAL_NAME}`,
                        `Company number: ${COMPANY_NUMBER}`,
                        `Registered office: ${COMPANY_ADDRESS}`,
                        `Email: ${COMPANY_EMAIL}`,
                    ]}
                />
            </PolicyWrapper>
        </>
    );
}
